# Test file for manual execution in vscode

### Filter for titles
# @jq .slideshow.slides | map({title})
GET https://httpbin.org/json

### Show Warning
# @jq .slideshow.slides | map({title
GET https://httpbin.org/json